// app/phrases.ts

export const noPhrases: string[] = [
  "No",
  "Are you sure?",
  "Paka kotha?",
  "Ki lo? Click korte parona?",
  "Arre try koro...",
  "Kopal e nai!",
  "Bhalobasha dorkar!",
  "Wrong choice, baby!",
  "Ekbar bhebe dekho...",
  "Hobe na bhai",
  "Error 404: No not found",
  "Try harder!",
  "Bhai, thak dorkar nai...",
  "Oops! Missed it.",
  "Click me if you can!",
  "Yes e click koro lokhi meye",
  "Still trying? 😂",
  "Persistence is key, but not here.",
  "Just give up already!",
  "Eto shoja",
  "Dhurrr!",
  "Kopal tai pora!",
  "Boka naki?",
  "তোমায় নিয়ে পালাবো",
  "সুইজারল্যান্ড যাবো",
  "না না, মাল্টা যাবো",
  "মাল্টা খাবো",
  "Asha chere dao",
  "এমন ছেলে হারালে",
  "কাঁদতে হবে আড়ালে",
  "Na bolle hobe?",
  "শোনো, জল ছলছল কাজল চোখের",
  "কন্যা সর্বনাশী, আমি তোমায় ভালোবাসি"
];